### ISSUE TITLE
Setting the time

### ISSUE THREAD

**Issue by jimwormold** [vtraveller/gowatt#3]
Thanks ever so much for providing this after Growatt monkeyed everything around!

Are you able to point me in the direction of setting the inverter time - mine drifts a bit, and I'd like to make sure it's set accurately before getting it to charge during my off peak hours.

Many thanks

**Comment by vtraveller** [comment]
yeah - so using the 'hack the website' technique we learn that its called 'pf_sys_year' and takes 'param1' plus the defaults.  I'll add it to the gowatt.py file.

That said, I've not found how to change the 'timezone' which is semi-invisible.  When I figure that out, I'll let you know.

```
def setTime(self,hour,min,date = datetime.today().strftime('%Y-%m-%d')):
  '''
  Sets the system time.
  
  Parameters:
    hour -> to set
    min  -> to set
    date -> override today's date (prob not needed)
  '''  

  settings = [
    '{} {}:{}'.format(date,hour,min)
  ]
  
  response = self.rawSet('pf_sys_year',settings)
  print(json.dumps(response)) # used to show working
  
  if not response or not 'msg' in response: return False

  if response['msg'] != 'inv_set_success':
    print('failed - NEED RECOVERY - ' + response['msg'])
    return False      

  return True
```

**Comment by jimwormold** [comment]
Just a little update - it looks like growatt want seconds specified too. I was getting a "inv_set_time_format"

For simplicity I just added 0 for seconds:
```
settings = [
    '{} {}:{}:0'.format(date,hour,min)
  ]
```
